AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Automatically build and deploy a single page application from a GitHub repository. Assets
  are hosted in S3 with a CloudFront CDN that provides SSL, a fallback (index.html) and
  automatic redirection from HTTP to HTTPS. A DNS alias that points at the CloudFront
  Distribution will be created in Route53.
  Example App URL: `example.com -> https://example.com`

  An Edge Optimized API Cloud Function will also be deployed with an API Gateway, DNS and SSL.
  Example API URL: `example.com -> https://api.example.com`
Parameters:
  # Common/Hosting
  EnvironmentType:
    Type: "String"
    Description: "The name of the environment to build under (NODE_ENV)"
    Default: "production"
  HostedZoneId:
    Type: "AWS::Route53::HostedZone::Id"
    Description: "Select the Hosted Zone"
  FullDomainName:
    Type: "String"
    Description: "A sub-domain to be created within the Hosted Zone (Example: app.example.com)"
  SSLCertificateARN:
    Type: "String"
    Description: "The ARN of the SSL Certificate (us-east-1 only)"
    AllowedPattern: "^.*?us-east-1.*"
    ConstraintDescription: "The certificate must be in the us-east-1 region."
  # UI Repo
  GitHubUser:
    Type: "String"
    Description: "The GitHub User that owns the repository"
  GitHubRepo:
    Type: "String"
    Description: "The name of the GitHub repository"
  GitHubBranch:
    Type: "String"
    Description: "The name of the branch to be built"
    Default: "master"
  GitHubToken:
    NoEcho: true
    Type: "String"
    Description: "A GitHub Access Token with `repo` permissions (https://github.com/settings/tokens)"
  # UI Build Options
  BuildType:
    Type: "String"
    Default: "LINUX_CONTAINER"
    Description: "The type of container that will be used for running the build"
  BuildComputeType:
    Type: "String"
    Default: "BUILD_GENERAL1_SMALL"
    Description: "The type/size of build compute configuration"
  BuildImage:
    Type: "String"
    Default: 'aws/codebuild/nodejs:10.14.1'
    Description: "The image needed to build the app"
  # API Repo
  APIGitHubUser:
    Type: "String"
    Description: "The GitHub User that owns the repository"
  APIGitHubRepo:
    Type: "String"
    Description: "The name of the GitHub repository"
  APIGitHubBranch:
    Type: "String"
    Description: "The name of the branch to be built"
    Default: "master"
  APIGitHubToken:
    NoEcho: true
    Type: "String"
    Description: "A GitHub Access Token with `repo` permissions (https://github.com/settings/tokens)"
  # API Build Options
  APIBuildType:
    Type: "String"
    Default: "LINUX_CONTAINER"
    Description: "The type of container that will be used for running the build"
  APIBuildComputeType:
    Type: "String"
    Default: "BUILD_GENERAL1_SMALL"
    Description: "The type/size of build compute configuration"
  APIBuildImage:
    Type: "String"
    Default: 'aws/codebuild/nodejs:10.14.1'
    Description: "The image needed to build the app"
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Hosting Configuration
        Parameters:
          - EnvironmentType
          - HostedZoneId
          - FullDomainName
          - SSLCertificateARN
      - Label:
          default: UI GitHub Settings
        Parameters:
          - GitHubToken
          - GitHubUser
          - GitHubRepo
          - GitHubBranch
      - Label:
          default: UI Build Settings
        Parameters:
          - BuildType
          - BuildComputeType
          - BuildImage
      - Label:
          default: API GitHub Settings
        Parameters:
          - APIGitHubToken
          - APIGitHubUser
          - APIGitHubRepo
          - APIGitHubBranch
      - Label:
          default: API Build Settings
        Parameters:
          - APIBuildType
          - APIBuildComputeType
          - APIBuildImage
    ParameterLabels:
      EnvironmentType:
        default: Environment Type
      HostedZoneId:
        default: Hosted Zone
      FullDomainName:
        default: Full Domain Name
      SSLCertificateARN:
        default: SSL Certificate ARN
      GitHubToken:
        default: UI GitHub Access Token
      GitHubUser:
        default: UI GitHub User (or Organization)
      GitHubRepo:
        default: UI GitHub Repository Name
      GitHubBranch:
        default: UI Build Branch
      BuildType:
        default: UI CodeBuild Build Type
      BuildComputeType:
        default: UI CodeBuild Compute Instance Type
      BuildImage:
        default: UI CodeBuild Build Image
      APIGitHubToken:
        default: API GitHub Access Token
      APIGitHubUser:
        default: API GitHub User (or Organization)
      APIGitHubRepo:
        default: API GitHub Repository Name
      APIGitHubBranch:
        default: API Build Branch
      APIBuildType:
        default: API CodeBuild Build Type
      APIBuildComputeType:
        default: API CodeBuild Compute Instance Type
      APIBuildImage:
        default: API CodeBuild Build Image
Resources:
  # API Products
  APIS3:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      BucketName:
        Fn::Sub:
          - "s3.api.${DomainName}"
          - DomainName: !Ref FullDomainName
  APICloudFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
  APICloudFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref APIS3
        S3Key: dist.zip
      Environment:
        Variables:
          NODE_ENV: !Ref EnvironmentType
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - APICloudFunctionRole
          - Arn
      Runtime: nodejs10.x
  APIGatewayRESTAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      EndpointConfiguration:
        Types:
          - EDGE
      Body:
        info:
          version: '1.0'
          title:
            Ref: AWS::StackName
        paths:
          "/":
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${APICloudFunction.Arn}/invocations
              responses: {}
        swagger: '2.0'
  APIGatewayRESTAPIDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: APIGatewayRESTAPI
      StageName: !Ref EnvironmentType
  APIGatewayRESTAPIEnvironment:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: APIGatewayRESTAPIDeployment
      RestApiId:
        Ref: APIGatewayRESTAPI
      StageName: !Ref EnvironmentType
  APICloudFunctionPOSTResourcePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      Principal: apigateway.amazonaws.com
      FunctionName:
        Ref: APICloudFunction
      SourceArn:
        Fn::Sub:
          - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/POST/
          - __Stage__: !Ref EnvironmentType
            __ApiId__:
              Ref: APIGatewayRESTAPI
  APIDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref SSLCertificateARN
      DomainName:
        Fn::Sub:
          - "api.${DomainName}."
          - DomainName: !Ref FullDomainName
      EndpointConfiguration:
        Types:
          - EDGE
      # RegionalCertificateArn: ''
  APIDomainNameBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: APIGatewayRESTAPI
    Properties:
      BasePath: '/'
      DomainName:
        Fn::Sub:
          - "api.${DomainName}."
          - DomainName: !Ref FullDomainName
      RestApiId:
        Ref: APIGatewayRESTAPI
      Stage: !Ref EnvironmentType
  APIRoute53Record:
    Type: "AWS::Route53::RecordSet"
    DependsOn: APIDomainName
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Type: A
      Name:
        Fn::Sub:
          - "api.${DomainName}."
          - DomainName: !Ref FullDomainName
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName:
          Fn::Sub:
            - "${DomainName}."
            - DomainName: !GetAtt APIDomainName.DistributionDomainName
  # API CI/CD
  APICodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
            Version: 2012-10-17
  APICodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: codepipeline-service
          PolicyDocument:
            Statement:
              - Action:
                  - 'codebuild:*'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:GetBucketVersioning'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 's3:PutObject'
                Resource:
                  - 'arn:aws:s3:::codepipeline*'
                Effect: Allow
              - Action:
                  - 's3:*'
                  - 'cloudformation:*'
                  - 'iam:PassRole'
                Resource: '*'
                Effect: Allow
            Version: 2012-10-17
  APIPipelineBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
  APICodeBuildDeploySite:
    Type: 'AWS::CodeBuild::Project'
    DependsOn:
      - APICodeBuildRole
      - APIS3
    Properties:
      Name: !Sub '${AWS::StackName}-BuildAndDeployAPI'
      Description: Deploy API to S3
      ServiceRole: !GetAtt APICodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref APIBuildType
        ComputeType: !Ref APIBuildComputeType
        Image: !Sub '${APIBuildImage}'
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.1
          phases:
            build:
              commands:
                - "npm i && npm i @resistdesign/jsx-compiler && NODE_ENV=${EnvironmentType} npx jsxc"
            post_build:
              commands:
                - aws s3 cp --recursive --acl private ./dist s3://s3.api.${FullDomainName}/
          artifacts:
            type: zip
            base-directory: 'dist'
            files:
                - '**/*'
      TimeoutInMinutes: 10
  APIPipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    DependsOn: APICodeBuildDeploySite
    Properties:
      RoleArn: !GetAtt APICodePipelineRole.Arn
      Stages:
        - Name: "Acquire-Source"
          Actions:
            - InputArtifacts: []
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref APIGitHubUser
                Repo: !Ref APIGitHubRepo
                Branch: !Ref APIGitHubBranch
                OAuthToken: !Ref APIGitHubToken
              RunOrder: 1
        - Name: "Build-And-Deploy"
          Actions:
            - Name: Artifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: DeployOutput
              Configuration:
                ProjectName: !Ref APICodeBuildDeploySite
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !Ref APIPipelineBucket
  # UI Products
  S3:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref FullDomainName
      WebsiteConfiguration:
        IndexDocument: index.html
  CloudFront:
    Type: "AWS::CloudFront::Distribution"
    DependsOn: S3
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref FullDomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificateARN
          SslSupportMethod: "sni-only"
          MinimumProtocolVersion: "TLSv1.1_2016"
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId:
            Fn::Sub:
              - "S3-${S3BucketName}"
              - S3BucketName: !Ref FullDomainName
          ViewerProtocolPolicy: "redirect-to-https"
        DefaultRootObject: "index.html"
        Enabled: true
        IPV6Enabled: false
        HttpVersion: "http2"
        Origins:
          - DomainName:
              Fn::Sub:
                - "${S3BucketName}.s3.amazonaws.com"
                - S3BucketName: !Ref FullDomainName
            Id:
              Fn::Sub:
                - "S3-${S3BucketName}"
                - S3BucketName: !Ref FullDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
        CustomErrorResponses:
          - ErrorCachingMinTTL: 300
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/index.html"
          - ErrorCachingMinTTL: 300
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: "/index.html"
        PriceClass: "PriceClass_All"
  Route53Record:
    Type: "AWS::Route53::RecordSet"
    DependsOn: CloudFront
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Type: A
      Name:
        Fn::Sub:
          - "${DomainName}."
          - DomainName: !Ref FullDomainName
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2
        DNSName:
          Fn::Sub:
            - "${DomainName}."
            - DomainName: !GetAtt CloudFront.DomainName
  # UI CI/CD
  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: codebuild-service
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
            Version: 2012-10-17
  CodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: codepipeline-service
          PolicyDocument:
            Statement:
              - Action:
                  - 'codebuild:*'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:GetBucketVersioning'
                Resource: '*'
                Effect: Allow
              - Action:
                  - 's3:PutObject'
                Resource:
                  - 'arn:aws:s3:::codepipeline*'
                Effect: Allow
              - Action:
                  - 's3:*'
                  - 'cloudformation:*'
                  - 'iam:PassRole'
                Resource: '*'
                Effect: Allow
            Version: 2012-10-17
  PipelineBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
  CodeBuildDeploySite:
    Type: 'AWS::CodeBuild::Project'
    DependsOn:
      - CodeBuildRole
      - S3
    Properties:
      Name: !Sub '${AWS::StackName}-BuildAndDeploySite'
      Description: Deploy site to S3
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref BuildType
        ComputeType: !Ref BuildComputeType
        Image: !Sub '${BuildImage}'
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.1
          phases:
            build:
              commands:
                - "npm i && npm i rdx && NODE_ENV=${EnvironmentType} npx rdx compile"
            post_build:
              commands:
                - aws s3 cp --recursive --acl public-read ./public s3://${FullDomainName}/
          artifacts:
            type: zip
            base-directory: 'public'
            files:
                - '**/*'
      TimeoutInMinutes: 10
  Pipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    DependsOn: CodeBuildDeploySite
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: "Acquire-Source"
          Actions:
            - InputArtifacts: []
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
              RunOrder: 1
        - Name: "Build-And-Deploy"
          Actions:
            - Name: Artifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: DeployOutput
              Configuration:
                ProjectName: !Ref CodeBuildDeploySite
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineBucket
Outputs:
  AppURL:
    Description: App URL
    Value: !Sub https://${FullDomainName}
  APIURL:
    Description: API URL
    Value: !Sub https://api.${FullDomainName}
